name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build the Website
      run: npm run build

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Get Stored Domain
      id: get-domain
      run: |
        DOMAIN=$(curl -s https://folio4ubackend-production.up.railway.app/get-subdomain | jq -r ".subdomain")
        if [ -z "$DOMAIN" ]; then
          echo "Error: No domain provided by the API"
          exit 1
        fi
        echo "Fetched DOMAIN: $DOMAIN"
        echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV

    - name: Deploy to Netlify
      run: |
        echo "Creating and deploying site: $DOMAIN"
        SITE_ID=$(netlify sites:create --name "$DOMAIN" --account-slug calibertech875 | grep -o "Site ID:  [a-zA-Z0-9-]*" | awk '{print $3}')
        echo "Created site with ID: $SITE_ID"
        netlify deploy --prod --dir=./dist --site="$SITE_ID" --auth="nfp_dmTjWcyc3W7KWMWepKDSnN2efxHq9kufe2f6"
      env:
        NETLIFY_AUTH_TOKEN: nfp_dmTjWcyc3W7KWMWepKDSnN2efxHq9kufe2f6
